kind: Service
apiVersion: v1
metadata:
  name: indexd-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      ambassador_id: "gen3"
      kind:  Mapping
      name:  indexd_mapping
      prefix: /index/
      service: http://indexd-service:80
spec:
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      name: http
      nodePort: null
    - protocol: TCP
      port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.service.httpsPort }}
      name: https
      nodePort: null
  type: {{ .Values.service.type }}
