kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-service
spec:
  selector:
    app: {{ .Chart.Name }}
    release: production
  ports:
    - protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      name: http
      nodePort: null
    - protocol: TCP
      port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.service.httpsPort }}
      name: https
      nodePort: null
  type: ClusterIP
